<?php

/**
 * @file
 * Provides a movie entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function movie_theme() {
  return [
    'movie' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for movie templates.
 *
 * Default template: movie.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the movie information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_movie(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
